name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Ruby (for bundler/Fastlane if needed)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.0.app
      - name: Install dependencies
        run: gem install bundler
      - name: Build app
        run: |
          xcodebuild clean build \
            -workspace Next Stop.xcworkspace \
            -scheme Next Stop \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest'
      - name: Run tests
        run: |
          xcodebuild test \
            -workspace Next Stop.xcworkspace \
            -scheme Next Stop \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest'
