name: Build and Test iOS App

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build_and_test:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Xcode Version
        run: |
          sudo xcode-select -s /Applications/Xcode_16.x.app/Contents/Developer
          
      - name: Install Dependencies
        run: |
          if [ -f "Podfile" ]; then
            sudo gem install cocoapods
            pod install
          fi
          
      - name: Build Project
        run: |
          xcodebuild clean \
            -project "Next Stop.xcodeproj" \
            -scheme "Next Stop" \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=iPhone 16,OS=18.2" \
            BUILD_DIR=$PWD/build

      - name: Run Tests
        run: |
          xcodebuild test \
            -project "Next Stop.xcodeproj" \
            -scheme "Next Stop" \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=iPhone 16,OS=18.2" \
            | tee result.log | tail -n 20


