name: Next Stop CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_project:
    runs-on: macos-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Xcode 16.3
        run: |
          sudo xcode-select --switch /Applications/Xcode_16.3.app
          sudo xcodebuild -runFirstLaunch

      - name: Install dependencies
        run: |
          brew install cocoapods
          pod install

      - name: Build and Test
        run: |
          xcodebuild -project "Next Stop.xcodeproj" \
                     -scheme "Next Stop" \
                     -sdk iphonesimulator \
                     -destination "platform=iOS Simulator,name=iPhone 16,OS=18.2" \
                     test || exit 1


