name: Next Stop CI

on:
  push:
    branches: [ main ] 
  pull_request:
    branches: [ main ]
    
jobs:
  build_project:
    runs-on: macos-latest
    steps:
      - name: Checkout-repository
        uses: actions/checkout@v2
        
      - name: Build-and-Test
        run: |
          xcodebuild \
            -project "Next Stop.xcodeproj" \
            -scheme "Next Stop" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.2' \
            test || exit 1

